version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: myappdb
    volumes:
      - mongo-data:/data/db

  backend:
    env_file: ./backend/.env.development
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/myappdb
    depends_on:
      - mongo

  frontend:
    env_file: ./frontend/.env.local
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
