name: Main Branch Deployment Check

on:
  push:
    branches:
      - main

jobs:
  verify-before-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Backend Docker Image
        run: docker build -t my-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t my-frontend ./frontend

      - name: Install Trivy
        run: |
          sudo apt-get install wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

      - name: Scan Backend with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-backend

      - name: Scan Frontend with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-frontend

      - name: Trigger Jenkins Deploy
        if: success()
        run: |
          curl -X POST "http://${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build?token=${{ secrets.JENKINS_DEPLOY_SECRET }}"
